openapi: 3.0.0
info:
  title: Simple API
  description: A simple API with a single endpoint
  version: 1.0.0

paths:
  /greet:
    get:
      summary: Returns a greeting message
      description: This endpoint returns a simple greeting message.
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!